// AUTO-GENERATED by scripts/generate_identities_js.py — do not edit manually
const CARD_LAYOUT = {
    "width": 1619,
    "height": 971,
    "photo": {
        "cx": 0.748,
        "cy": 0.4616,
        "r": 0.152
    },
    "name": {
        "x": 0.408,
        "y": 0.535,
        "maxWidth": 0.165,
        "fontSize": 0.036
    },
    "field2": {
        "x": 0.355,
        "y": 0.702,
        "maxWidth": 0.22,
        "fontSize": 0.032
    },
    "pronouns": {
        "x": 0.355,
        "y": 0.598,
        "fontSize": 0.018,
        "enabled": false
    }
};

const PHOTO_LAYOUTS = {
    "abrosexual": {
        "cx": 0.7599,
        "cy": 0.4486,
        "r": 0.1623
    },
    "ace-aro-variant": {
        "cx": 0.7504,
        "cy": 0.4553,
        "r": 0.1628
    },
    "ace-aro": {
        "cx": 0.7446,
        "cy": 0.4559,
        "r": 0.1631
    },
    "aceflux": {
        "cx": 0.7547,
        "cy": 0.4465,
        "r": 0.1611
    },
    "achillean": {
        "cx": 0.7583,
        "cy": 0.4632,
        "r": 0.1641
    },
    "aegosexual": {
        "cx": 0.7512,
        "cy": 0.4519,
        "r": 0.1617
    },
    "ally": {
        "cx": 0.749,
        "cy": 0.4569,
        "r": 0.1635
    },
    "androsexual": {
        "cx": 0.7588,
        "cy": 0.45,
        "r": 0.1614
    },
    "apothisexual": {
        "cx": 0.7559,
        "cy": 0.453,
        "r": 0.164
    },
    "aroflux": {
        "cx": 0.7505,
        "cy": 0.4665,
        "r": 0.1634
    },
    "aromantic": {
        "cx": 0.7536,
        "cy": 0.4575,
        "r": 0.1637
    },
    "bellusromantic": {
        "cx": 0.7461,
        "cy": 0.4411,
        "r": 0.1608
    },
    "bigender": {
        "cx": 0.7636,
        "cy": 0.4583,
        "r": 0.164
    },
    "bisexual": {
        "cx": 0.7529,
        "cy": 0.4577,
        "r": 0.1636
    },
    "ceterosexual": {
        "cx": 0.7505,
        "cy": 0.4418,
        "r": 0.1635
    },
    "cupioromantic": {
        "cx": 0.7551,
        "cy": 0.4577,
        "r": 0.163
    },
    "cupiosexual": {
        "cx": 0.7559,
        "cy": 0.4528,
        "r": 0.1618
    },
    "demiboy": {
        "cx": 0.757,
        "cy": 0.4551,
        "r": 0.1645
    },
    "demigender": {
        "cx": 0.7483,
        "cy": 0.4476,
        "r": 0.1613
    },
    "demigirl": {
        "cx": 0.7485,
        "cy": 0.4359,
        "r": 0.1616
    },
    "demiromantic": {
        "cx": 0.7511,
        "cy": 0.4595,
        "r": 0.1639
    },
    "diamoric": {
        "cx": 0.7633,
        "cy": 0.4477,
        "r": 0.1661
    },
    "frayromantic": {
        "cx": 0.749,
        "cy": 0.4531,
        "r": 0.1634
    },
    "fraysexual": {
        "cx": 0.7493,
        "cy": 0.4591,
        "r": 0.163
    },
    "gay": {
        "cx": 0.7528,
        "cy": 0.4595,
        "r": 0.1658
    },
    "greyromantic": {
        "cx": 0.7548,
        "cy": 0.4587,
        "r": 0.1639
    },
    "greysexual": {
        "cx": 0.7543,
        "cy": 0.4552,
        "r": 0.164
    },
    "gynesexual": {
        "cx": 0.7572,
        "cy": 0.4515,
        "r": 0.1661
    },
    "intersex": {
        "cx": 0.7408,
        "cy": 0.4611,
        "r": 0.1657
    },
    "lesbian": {
        "cx": 0.7559,
        "cy": 0.4579,
        "r": 0.1636
    },
    "lgbtqia-plus": {
        "cx": 0.7524,
        "cy": 0.4593,
        "r": 0.1631
    },
    "lithromantic": {
        "cx": 0.7474,
        "cy": 0.4577,
        "r": 0.1643
    },
    "lithsexual": {
        "cx": 0.7545,
        "cy": 0.4562,
        "r": 0.1635
    },
    "neptunic": {
        "cx": 0.7493,
        "cy": 0.4566,
        "r": 0.1608
    },
    "omnisexual": {
        "cx": 0.7587,
        "cy": 0.4505,
        "r": 0.1638
    },
    "pangender": {
        "cx": 0.7623,
        "cy": 0.4615,
        "r": 0.1639
    },
    "polygender": {
        "cx": 0.7605,
        "cy": 0.4542,
        "r": 0.1636
    },
    "polysexual": {
        "cx": 0.7571,
        "cy": 0.4509,
        "r": 0.1634
    },
    "pride": {
        "cx": 0.748,
        "cy": 0.4616,
        "r": 0.1643
    },
    "queer": {
        "cx": 0.7496,
        "cy": 0.4631,
        "r": 0.1641
    },
    "queerplatonic": {
        "cx": 0.7486,
        "cy": 0.4514,
        "r": 0.1603
    },
    "questioning": {
        "cx": 0.7539,
        "cy": 0.4563,
        "r": 0.1625
    },
    "quoiromantic": {
        "cx": 0.7591,
        "cy": 0.4588,
        "r": 0.163
    },
    "recipromantic": {
        "cx": 0.7463,
        "cy": 0.4404,
        "r": 0.1616
    },
    "reciprosexual": {
        "cx": 0.7552,
        "cy": 0.4535,
        "r": 0.1629
    },
    "sapphic": {
        "cx": 0.7592,
        "cy": 0.458,
        "r": 0.1627
    },
    "toric": {
        "cx": 0.7589,
        "cy": 0.452,
        "r": 0.1635
    },
    "trans-gender-diverse": {
        "cx": 0.7441,
        "cy": 0.4558,
        "r": 0.1649
    },
    "trigender": {
        "cx": 0.7589,
        "cy": 0.4636,
        "r": 0.164
    },
    "trixic": {
        "cx": 0.7491,
        "cy": 0.4599,
        "r": 0.165
    },
    "uranic": {
        "cx": 0.7546,
        "cy": 0.4489,
        "r": 0.1646
    },
    "vincian": {
        "cx": 0.7621,
        "cy": 0.4669,
        "r": 0.163
    }
};

const PRONOUNS = ["they/them", "she/her", "he/him", "she/they", "he/they", "any pronouns", "name only", "ze/hir", "xe/xem"];

const CORE_IDENTITIES = [
    {
        "id": "pride",
        "label": "Pride",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "ally",
        "label": "Ally",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "trans-gender-diverse",
        "label": "Trans & Gender Diverse",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "intersex",
        "label": "Intersex",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "ace-aro",
        "label": "Ace & Aro",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "lgbtqia-plus",
        "label": "LGBTQIA+",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "lesbian",
        "label": "Lesbian",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "gay",
        "label": "Gay",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "bisexual",
        "label": "Bisexual / Bi",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "queer",
        "label": "Queer",
        "category": "Core",
        "fieldType": "community"
    },
    {
        "id": "questioning",
        "label": "Questioning",
        "category": "Core",
        "fieldType": "community"
    }
];

const SEXUAL_IDENTITIES = [
    {
        "id": "omnisexual",
        "label": "Omnisexual",
        "meaning": "Attracted to all genders, often with gender still being noticed.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "polysexual",
        "label": "Polysexual",
        "meaning": "Attracted to multiple genders, not necessarily all.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "abrosexual",
        "label": "Abrosexual",
        "meaning": "Sexuality shifts or changes over time.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "greysexual",
        "label": "Greysexual / Grey-A",
        "aliases": [
            "grey-a",
            "grey a"
        ],
        "meaning": "Rare or limited sexual attraction.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "aegosexual",
        "label": "Aegosexual",
        "meaning": "May enjoy sexual fantasy/content but not want direct sexual involvement.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "cupiosexual",
        "label": "Cupiosexual",
        "meaning": "Does not feel sexual attraction but may still want a sexual relationship.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "lithsexual",
        "label": "Lithsexual / Akoisexual",
        "aliases": [
            "akoisexual"
        ],
        "meaning": "Attraction may fade if it is returned.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "fraysexual",
        "label": "Fraysexual",
        "meaning": "Attraction fades after emotional closeness develops.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "reciprosexual",
        "label": "Reciprosexual",
        "meaning": "Only feels attraction after knowing attraction is returned.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "apothisexual",
        "label": "Apothisexual",
        "meaning": "Asexual and sex-repulsed.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "aceflux",
        "label": "Aceflux",
        "meaning": "Asexual-spectrum identity that fluctuates.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "androsexual",
        "label": "Androsexual",
        "meaning": "Attraction to masculinity/men/masc-presenting people.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "gynesexual",
        "label": "Gynesexual / Gynosexual",
        "aliases": [
            "gynosexual"
        ],
        "meaning": "Attraction to femininity/women/femme-presenting people.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "ceterosexual",
        "label": "Ceterosexual / Skoliosexual",
        "aliases": [
            "skoliosexual"
        ],
        "meaning": "Attraction to non-binary or gender-diverse people.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "uranic",
        "label": "Uranic",
        "meaning": "Attraction to men, masculine people, and/or non-binary people, not women.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "neptunic",
        "label": "Neptunic",
        "meaning": "Attraction to women, feminine people, and/or non-binary people, not men.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "toric",
        "label": "Toric",
        "meaning": "Non-binary person attracted to men.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "trixic",
        "label": "Trixic",
        "meaning": "Non-binary person attracted to women.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "diamoric",
        "label": "Diamoric",
        "meaning": "Attraction/relationship involving non-binary people, not easily described as straight/gay.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "sapphic",
        "label": "Sapphic",
        "meaning": "Women/feminine-aligned people attracted to women.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "achillean",
        "label": "Achillean / MLM",
        "aliases": [
            "mlm"
        ],
        "meaning": "Men/masculine-aligned people attracted to men.",
        "category": "Sexuality",
        "fieldType": "community"
    },
    {
        "id": "vincian",
        "label": "Vincian",
        "meaning": "Another term for gay men / men-loving-men.",
        "category": "Sexuality",
        "fieldType": "community"
    }
];

const ROMANTIC_IDENTITIES = [
    {
        "id": "aromantic",
        "label": "Aromantic / Aro",
        "aliases": [
            "aro"
        ],
        "meaning": "Little or no romantic attraction.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "greyromantic",
        "label": "Greyromantic",
        "meaning": "Rare or limited romantic attraction.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "demiromantic",
        "label": "Demiromantic",
        "meaning": "Romantic attraction after strong emotional connection.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "aroflux",
        "label": "Aroflux",
        "meaning": "Romantic attraction fluctuates.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "cupioromantic",
        "label": "Cupioromantic",
        "meaning": "Does not feel romantic attraction but may still want a romantic relationship.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "lithromantic",
        "label": "Lithromantic / Akoisromantic",
        "aliases": [
            "akoisromantic"
        ],
        "meaning": "Romantic attraction may fade if returned.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "frayromantic",
        "label": "Frayromantic",
        "meaning": "Romantic attraction fades after closeness develops.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "recipromantic",
        "label": "Recipromantic",
        "meaning": "Romantic attraction only after knowing it is returned.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "quoiromantic",
        "label": "Quoiromantic / WTFromantic",
        "aliases": [
            "wtfromantic"
        ],
        "meaning": "Hard to tell whether attraction is romantic, platonic, or something else.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "bellusromantic",
        "label": "Bellusromantic",
        "meaning": "Likes romantic gestures/aesthetic but may not want a romantic relationship.",
        "category": "Romantic",
        "fieldType": "community"
    },
    {
        "id": "queerplatonic",
        "label": "Queerplatonic",
        "meaning": "A deep committed bond that is not easily friendship or romance.",
        "category": "Romantic",
        "fieldType": "community"
    }
];

const GENDER_IDENTITIES = [
    {
        "id": "demigirl",
        "label": "Demigirl",
        "meaning": "Partly, but not fully, girl/woman.",
        "category": "Gender",
        "fieldType": "community"
    },
    {
        "id": "demiboy",
        "label": "Demiboy",
        "meaning": "Partly, but not fully, boy/man.",
        "category": "Gender",
        "fieldType": "community"
    },
    {
        "id": "demigender",
        "label": "Demigender",
        "meaning": "Partial connection to a gender.",
        "category": "Gender",
        "fieldType": "community"
    },
    {
        "id": "bigender",
        "label": "Bigender",
        "meaning": "Two genders.",
        "category": "Gender",
        "fieldType": "community"
    },
    {
        "id": "trigender",
        "label": "Trigender",
        "meaning": "Three genders.",
        "category": "Gender",
        "fieldType": "community"
    },
    {
        "id": "polygender",
        "label": "Polygender",
        "meaning": "Multiple genders.",
        "category": "Gender",
        "fieldType": "community"
    },
    {
        "id": "pangender",
        "label": "Pangender",
        "meaning": "Many/all genders.",
        "category": "Gender",
        "fieldType": "community"
    }
];

const ALL_IDENTITIES = [
    ...CORE_IDENTITIES,
    ...SEXUAL_IDENTITIES,
    ...ROMANTIC_IDENTITIES,
    ...GENDER_IDENTITIES
];

const IDENTITY_BY_ID = Object.fromEntries(ALL_IDENTITIES.map(i => [i.id, i]));

function normalizeKey(value) {
    return String(value || '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
}

function resolveIdentity(input) {
    if (!input) return null;
    const raw = String(input).trim();
    const key = normalizeKey(raw);

    for (const identity of ALL_IDENTITIES) {
        if (identity.id === key || normalizeKey(identity.label) === key) return identity;
        for (const alias of identity.aliases || []) {
            if (normalizeKey(alias) === key) return identity;
        }
    }
    return null;
}

function getIdentityImagePath(identityId) {
    return `assets/cards/${identityId}.png`;
}

function getPhotoLayout(identityId) {
    return PHOTO_LAYOUTS[identityId] || CARD_LAYOUT.photo;
}
