"""Generate js/identities.js and data/identities.json from Python source of truth."""
import json
from pathlib import Path

from identities_data import (
    CARD_LAYOUT,
    CORE_IDENTITIES,
    GENDER_IDENTITIES,
    PRONOUNS,
    ROMANTIC_IDENTITIES,
    SEXUAL_IDENTITIES,
    all_identities,
)

ROOT = Path(__file__).resolve().parent.parent


def js_string(s):
    return json.dumps(s)


def js_object(obj, indent=0):
    sp = " " * indent
    if isinstance(obj, dict):
        lines = ["{"]
        items = list(obj.items())
        for i, (k, v) in enumerate(items):
            comma = "," if i < len(items) - 1 else ""
            if isinstance(v, (dict, list)):
                lines.append(f"{sp}    {k}: {js_object(v, indent + 4)}{comma}")
            else:
                lines.append(f"{sp}    {k}: {json.dumps(v)}{comma}")
        lines.append(f"{sp}}}")
        return "\n".join(lines)
    if isinstance(obj, list):
        if not obj:
            return "[]"
        if isinstance(obj[0], dict):
            parts = [js_object(x, indent + 4) for x in obj]
            inner = (",\n" + " " * (indent + 4)).join(parts)
            return f"[\n{' ' * (indent + 4)}{inner}\n{sp}]"
        return json.dumps(obj)
    return json.dumps(obj)


def main():
    data_dir = ROOT / "data"
    data_dir.mkdir(exist_ok=True)

    payload = {
        "cardLayout": CARD_LAYOUT,
        "pronouns": PRONOUNS,
        "coreIdentities": CORE_IDENTITIES,
        "sexualIdentities": [{**i, "category": "Sexuality", "fieldType": "community"} for i in SEXUAL_IDENTITIES],
        "romanticIdentities": [{**i, "category": "Romantic", "fieldType": "community"} for i in ROMANTIC_IDENTITIES],
        "genderIdentities": [{**i, "category": "Gender", "fieldType": "community"} for i in GENDER_IDENTITIES],
        "allIdentities": all_identities(),
    }
    (data_dir / "identities.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")

    js = f"""// AUTO-GENERATED by scripts/generate_identities_js.py — do not edit manually
const CARD_LAYOUT = {json.dumps(CARD_LAYOUT, indent=4)};

const PRONOUNS = {json.dumps(PRONOUNS)};

const CORE_IDENTITIES = {json.dumps(CORE_IDENTITIES, indent=4)};

const SEXUAL_IDENTITIES = {json.dumps(payload['sexualIdentities'], indent=4)};

const ROMANTIC_IDENTITIES = {json.dumps(payload['romanticIdentities'], indent=4)};

const GENDER_IDENTITIES = {json.dumps(payload['genderIdentities'], indent=4)};

const ALL_IDENTITIES = [
    ...CORE_IDENTITIES,
    ...SEXUAL_IDENTITIES,
    ...ROMANTIC_IDENTITIES,
    ...GENDER_IDENTITIES
];

const IDENTITY_BY_ID = Object.fromEntries(ALL_IDENTITIES.map(i => [i.id, i]));

function normalizeKey(value) {{
    return String(value || '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
}}

function resolveIdentity(input) {{
    if (!input) return null;
    const raw = String(input).trim();
    const key = normalizeKey(raw);

    for (const identity of ALL_IDENTITIES) {{
        if (identity.id === key || normalizeKey(identity.label) === key) return identity;
        for (const alias of identity.aliases || []) {{
            if (normalizeKey(alias) === key) return identity;
        }}
    }}
    return null;
}}

function getIdentityImagePath(identityId) {{
    return `assets/cards/${{identityId}}.png`;
}}
"""
    (ROOT / "js" / "identities.js").write_text(js, encoding="utf-8")
    print(f"Generated js/identities.js and data/identities.json ({len(all_identities())} identities)")


if __name__ == "__main__":
    main()